version: '3.8'

services:
  set-nx:
    build:
      target: dev-attached
      args:
        USER_GID: 20
        USER_UID: 501
    volumes:
      # - .docker/home/:/home/node/
      - ~/.ssh:/home/node/.ssh:ro
      - ~/.gnupg/pubring.kbx:/home/node/.gnupg/pubring.kbx:ro
      - ~/.gnupg/private-keys-v1.d:/home/node/.gnupg/private-keys-v1.d:ro
      - ~/.gitconfig:/home/node/.gitconfig
      - .docker/.p10k.zsh:/home/node/.p10k.zsh
      - .docker/.zsh_history:/home/node/.zsh_history
      - .docker/.zshrc:/home/node/.zshrc
      - .docker/zsh-syntax-highlighting:/home/node/zsh-syntax-highlighting
